// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ComerBasicResponse struct {
	Activation     bool   `json:"activation"`
	Address        string `json:"address"`
	Avatar         string `json:"avatar"`
	Banner         string `json:"banner"`
	CustomDomain   string `json:"custom_domain"`
	Id             int    `json:"id"`
	InvitationCode string `json:"invitation_code"`
	IsConnected    bool   `json:"is_connected"`
	Location       string `json:"location"`
	Name           string `json:"name"`
	TimeZone       string `json:"time_zone"`
}


type IsConnectedResponse struct {
	IsConnected bool `json:"is_connected"`
}

type IsExistResponse struct {
	IsExist bool `json:"is_exist"`
}

type ProjectCountResponse struct {
	BountyCount        int `json:"bounty_count"`
	CrowdfundingCount  int `json:"crowdfunding_count"`
	GovernanceCount    int `json:"governance_count"`
	OtherDappCount     int `json:"other_dapp_count"`
	SaleLaunchpadCount int `json:"sale_launchpad_count"`
	StartupCount       int `json:"startup_count"`
}

type ThirdPartyVerifyResponse struct {
	Verify bool `json:"verify"`
}
