// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ComerInfoDetailResponse struct {
	Accounts       []ComerAccountResponse      `json:"accounts"`
	Activation     bool                        `json:"activation"`
	Address        string                      `json:"address"`
	Avatar         string                      `json:"avatar"`
	Banner         string                      `json:"banner"`
	ConnectedTotal ComerConnectedTotalResponse `json:"connected_total"`
	CustomDomain   string                      `json:"custom_domain"`
	Educations     []ComerEducation            `json:"educations"`
	Id             int                         `json:"id"`
	Info           ComerInfo                   `json:"info"`
	InvitationCode string                      `json:"invitation_code"`
	IsConnected    bool                        `json:"is_connected"`
	Languages      []ComerLanguageResponse     `json:"languages"`
	Location       string                      `json:"location"`
	Name           string                      `json:"name"`
	Skills         []TagRelationResponse       `json:"skills"`
	Socials        []SocialBookResponse        `json:"socials"`
	TimeZone       string                      `json:"time_zone"`
}

type ComerInvitationCountResponse struct {
	ActivatedTotal int `json:"activated_total"`
	InactiveTotal  int `json:"inactive_total"`
}

type ComerResponse struct {
	Activation     bool   `json:"activation"`
	Address        string `json:"address"`
	Avatar         string `json:"avatar"`
	Banner         string `json:"banner"`
	CustomDomain   string `json:"custom_domain"`
	Id             int    `json:"id"`
	InvitationCode string `json:"invitation_code"`
	IsConnected    bool   `json:"is_connected"`
	IsSeted        bool   `json:"is_seted"`
	Location       string `json:"location"`
	Name           string `json:"name"`
	TimeZone       string `json:"time_zone"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type PageData struct {
	List  []interface{} `json:"list"`
	Page  int           `json:"page"`
	Size  int           `json:"size"`
	Total int           `json:"total"`
}

type StartupListResponse struct {
	List  []SimpleStartupInfo `json:"list"`
	Total int                 `json:"total"`
}

type UpdateComerInfoRequest struct {
	ComerId    int64  `json:"comer_id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	Cover      string `json:"cover"`
	Location   string `json:"location"`
	TimeZone   string `json:"time_zone"`
	Website    string `json:"website"`
	Email      string `json:"email"`
	Twitter    string `json:"twitter"`
	Discord    string `json:"discord"`
	Telegram   string `json:"telegram"`
	Medium     string `json:"medium"`
	Facebook   string `json:"facebook"`
	Linktree   string `json:"linktree"`
	Bio        string `json:"bio"`
	Languages  string `json:"languages"`
	Educations string `json:"educations"`
}
