// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ListResponse struct {
	Page  int64         `json:"page"`
	Size  int64         `json:"size"`
	Total int64         `json:"total"`
	List  []TagResponse `json:"list"`
}
